### ISSUE TITLE
Fails to parse apt gpg keyrings

### ISSUE THREAD

**Issue by mmstick** [FauxFaux/gpgrv#1]
Getting parsing errors when trying to load keys from `/etc/apt/trusted.gpg`:

```rust
use gpgrv::Keyring;
use std::io;
use std::fs::File;
use std::ops::Deref;

pub struct AptKeyring(Keyring);

impl AptKeyring {
    pub fn new() -> io::Result<Self> {
        let mut keyring = Keyring::new();
        keyring.append_keys_from(File::open("/etc/apt/trusted.gpg")?)
            .map_err(|why| io::Error::new(
                io::ErrorKind::Other,
                format!("failed to add keys from keyring at /etc/apt/trusted.gpg: {}", why)
            ))?;

        Ok(AptKeyring(keyring))
    }
}

impl Deref for AptKeyring {
    type Target = Keyring;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
```

```
failed to add keys from keyring at /etc/apt/trusted.gpg: parsing after after Some(\"c2e73424d59097ab\") at around 2748
```

**Comment by FauxFaux** [comment]
I'm happy to look at this. Can you share your `/etc/apt/trusted.gpg`?

It shouldn't have any sensitive information in, except perhaps a list of which PPAs and 3rd party repos you have enabled. I'll also see if I can work out if we can get a better log than that...

**Comment by FauxFaux** [comment]
I see the error as:

```
...`Err` value: ErrorMessage { msg: "not supported: packet tag: 12, len: 12" }

parsing after after Some("c2e73424d59097ab") at around 2748', libcore/result.rs:1009:5
```

Not sure why you're losing the cause information, but it doesn't matter, as I can reproduce it.

`packet tag: 12` is "trust" information, which I think `gpgv` just ignores? Let's ignore it, to start with.

**Comment by mmstick** [comment]
Thanks! This makes us one step closer to an `apt` replacement in Rust. Now just need to get a hyper bug resolved.

**Comment by FauxFaux** [comment]
I actually wrote a good chunk of `apt`, if you haven't seen it: https://github.com/FauxFaux/fapt

No resolver or actual installation step.

**Comment by mmstick** [comment]
You may be interested in some of our crates, then: https://github.com/pop-os?language=rust
