### ISSUE TITLE
Expects newline on signature-ending line

### ISSUE THREAD

**Issue by OddBloke** [FauxFaux/gpgrv#4]
Which Artifactory's Debian metadata does not include (`%` is zsh indicating the lack of a newline):

```
$ tail -n1 ~/.cache/fapt/lists/https__artifactory.redacted_443_artifactory_deb-prod-local__jammy_InRelease
-----END PGP SIGNATURE-----%
$ tail -n1 ~/.cache/fapt/lists/http__ca.archive.ubuntu.com_80_ubuntu__jammy_InRelease
-----END PGP SIGNATURE-----
```

This results in a panic with `empty read after: "-----END PGP SIGNATURE-----"`.

**Comment by FauxFaux** [comment]
Fixed in 82f6eb856db99bb564832043251b9ec00f976ad1.
